## Clase 20/04/22 Numpy

In [1]:
import numpy as np

Con la semilla `seed` se obtienen los mismos numeros aleatorios

In [20]:
np.random.seed(0)
x1 = np.random.randint(10, size = 10)
x2 = np.random.randint(10, size = (3,3))
x3 = np.random.randint(10, size = (3,4,5))

In [10]:
print(x1,'\n')
print(x2,'\n')
print(x3,'\n')

[5 0 3 3 7 9 3 5 2 4] 

[[7 6 8]
 [8 1 6]
 [7 7 8]] 

[[[1 5 9 8 9]
  [4 3 0 3 5]
  [0 2 3 8 1]
  [3 3 3 7 0]]

 [[1 9 9 0 4]
  [7 3 2 7 2]
  [0 0 4 5 5]
  [6 8 4 1 4]]

 [[9 8 1 1 7]
  [9 9 3 6 7]
  [2 0 3 5 9]
  [4 4 6 4 4]]] 



In [4]:
# Identacion
numeros = np.array([1,2,3,4])

numeros[1]

2

## Clase 21/04/22

Slice: Nos ayuda a seleccionar cierta porción de información qué queremos, son como las rebanadas de un pastel.

### Slices unidimensionales

In [10]:
# Arreglo en base a un range
x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Ahora si quisieramos separar en dos ese arreglo, podemos usar la siguiente notacion

In [8]:
# Si quiero desde el inicio hasta la posicion 5
x[:5]

array([0, 1, 2, 3, 4])

In [9]:
# Elementos a partir de la posicion 5 al final
x[5:]

array([5, 6, 7, 8, 9])

Ahora para ir saltando posiciones

In [11]:
# Obtener los elementos de la posicion 2 a la 7 
# x[start:stop:step]

x[2:7:2]

array([2, 4, 6])

Revertimos ahora el arreglo

In [12]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [15]:
# Ahora para ver solo los pares
pares = x[2:7:2]

pares[::-1]

array([6, 4, 2])

### Slices multidimensionales

In [16]:
data = np.array([np.arange(i*5,i*5+5) for i in range(5)])
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
# Para movernos entre la data
# data[row][column] 

data[2][1]

11

In [18]:
# Otra forma que se puede hacer con numpy es
data[2,1]

11

In [19]:
# Obtener las primeras dos filas y tres columnas
data[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

### Retos 

- Obtener los elementos de las filas 4-7 y columnas 2-8
- Obtener los elementos de las filas 0-5 y columnas 0-3
- Obtener los elementos de las ultimas 3 filas y las ultimas 5 columnas

In [5]:
np.random.seed(0) #para mantener los mismos datos

# Creamos matriz aleatoria
random_data = np.random.randint(10, size=(10,10))
random_data

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])

In [3]:
# Obtener los elementos de las filas 4-7 y columnas 2-8
array1 = random_data[4:7,2:8]
array1

array([[0, 4, 7, 3, 2, 7],
       [5, 5, 6, 8, 4, 1],
       [1, 7, 9, 9, 3, 6]])

In [4]:
# Obtener los elementos de las filas 0-5 y columnas 0-3
array2 = random_data[:5,:3]
array2

array([[5, 0, 3],
       [7, 6, 8],
       [5, 9, 8],
       [2, 3, 8],
       [9, 9, 0]])

In [6]:
# Obtener los elementos de las ultimas 3 filas y las ultimas 5 columnas
random_data[-3:,-5:] # esta instruccion modifica a random_data

array([[4, 6, 4, 4, 3],
       [7, 5, 5, 0, 1],
       [0, 1, 2, 4, 2]])

In [10]:
# Para evitarlo, usariamos .copy() para hacer una copia
copia = random_data[-3:,-5:]
copia

array([[4, 6, 4, 4, 3],
       [7, 5, 5, 0, 1],
       [0, 1, 2, 4, 2]])

### Concatenar matrices

In [11]:
x = np.array([1,2,3])
y = np.array([3,2,1])

np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [12]:
# Uniendo matrices
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[1,2,3],[4,5,6]])

# axis = 0
np.concatenate([m1,m2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [14]:
# axis = 1
np.concatenate([m1,m2], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [16]:
# Otra forma
np.c_[m1,m2]

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Dividir matrices

In [28]:
array = [12, 34, 2, 1, 67, 78, 7, 34, 1]

x1, x2, x3 = np.split(array,[2,4])
print(x1)
print(x2)
print(x3)

[12 34]
[2 1]
[67 78  7 34  1]


In [29]:
# Cambiar las dimensiones del array
array_reshape = np.array(array).reshape((3,3))
array_reshape

array([[12, 34,  2],
       [ 1, 67, 78],
       [ 7, 34,  1]])

In [35]:
# Dividir array
upper, lower = np.vsplit(array_reshape,[2])
print(upper)
print('------------')
print(lower)

[[12 34  2]
 [ 1 67 78]]
------------
[[ 7 34  1]]


## Universal Functions

In [2]:
np.random.seed(0) #para mantener los mismos datos

values = np.random.randint(1,100,size=100)
values

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89, 89, 13, 59, 66, 40,
       88, 47, 89, 82, 38, 26, 78, 73, 10, 21, 81, 70, 80, 48, 65, 83, 89,
       50, 30, 20, 20, 15, 40, 33, 66, 10, 58, 33, 32, 75, 24, 36, 76, 56,
       29, 35,  1,  1, 37, 54,  6, 39, 18, 80,  5, 43, 59, 32,  2, 66, 42,
       58, 36, 12, 47, 83, 92,  1, 15, 54, 13, 43, 85, 76, 69,  7, 69, 48,
        4, 77, 53, 79, 16, 21, 59, 24, 80, 14, 86, 49, 50, 70, 42])

In [3]:
def reduce_10_percent(data):
    result = []
    for number in data:
        reduce = number * 0.9
        result.append(reduce)
    return result

In [9]:
reduce_10_percent(values)

[40.5,
 43.2,
 58.5,
 61.2,
 61.2,
 9.0,
 75.60000000000001,
 19.8,
 33.300000000000004,
 79.2,
 63.9,
 80.10000000000001,
 80.10000000000001,
 11.700000000000001,
 53.1,
 59.4,
 36.0,
 79.2,
 42.300000000000004,
 80.10000000000001,
 73.8,
 34.2,
 23.400000000000002,
 70.2,
 65.7,
 9.0,
 18.900000000000002,
 72.9,
 63.0,
 72.0,
 43.2,
 58.5,
 74.7,
 80.10000000000001,
 45.0,
 27.0,
 18.0,
 18.0,
 13.5,
 36.0,
 29.7,
 59.4,
 9.0,
 52.2,
 29.7,
 28.8,
 67.5,
 21.6,
 32.4,
 68.4,
 50.4,
 26.1,
 31.5,
 0.9,
 0.9,
 33.300000000000004,
 48.6,
 5.4,
 35.1,
 16.2,
 72.0,
 4.5,
 38.7,
 53.1,
 28.8,
 1.8,
 59.4,
 37.800000000000004,
 52.2,
 32.4,
 10.8,
 42.300000000000004,
 74.7,
 82.8,
 0.9,
 13.5,
 48.6,
 11.700000000000001,
 38.7,
 76.5,
 68.4,
 62.1,
 6.3,
 62.1,
 43.2,
 3.6,
 69.3,
 47.7,
 71.10000000000001,
 14.4,
 18.900000000000002,
 53.1,
 21.6,
 72.0,
 12.6,
 77.4,
 44.1,
 45.0,
 63.0,
 37.800000000000004]

¿Cuanto tiempo tarda en hacerlo? 

In [8]:
%timeit reduce_10_percent(values)

389 µs ± 39.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Ahora realicemos el mismo procedimiento con las Ufunc

In [10]:
resultu = values*0.9
resultu

array([40.5, 43.2, 58.5, 61.2, 61.2,  9. , 75.6, 19.8, 33.3, 79.2, 63.9,
       80.1, 80.1, 11.7, 53.1, 59.4, 36. , 79.2, 42.3, 80.1, 73.8, 34.2,
       23.4, 70.2, 65.7,  9. , 18.9, 72.9, 63. , 72. , 43.2, 58.5, 74.7,
       80.1, 45. , 27. , 18. , 18. , 13.5, 36. , 29.7, 59.4,  9. , 52.2,
       29.7, 28.8, 67.5, 21.6, 32.4, 68.4, 50.4, 26.1, 31.5,  0.9,  0.9,
       33.3, 48.6,  5.4, 35.1, 16.2, 72. ,  4.5, 38.7, 53.1, 28.8,  1.8,
       59.4, 37.8, 52.2, 32.4, 10.8, 42.3, 74.7, 82.8,  0.9, 13.5, 48.6,
       11.7, 38.7, 76.5, 68.4, 62.1,  6.3, 62.1, 43.2,  3.6, 69.3, 47.7,
       71.1, 14.4, 18.9, 53.1, 21.6, 72. , 12.6, 77.4, 44.1, 45. , 63. ,
       37.8])

¿Cuánto tarda?

In [11]:
%timeit (values*0.9)

2.45 µs ± 431 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


**Es más eficiente y sencillo trabajar con Numpy**

Ejemplos de opeaciones


In [12]:
X = np.arange(5)
X

array([0, 1, 2, 3, 4])

In [13]:
X-5

array([-5, -4, -3, -2, -1])

In [14]:
X*2

array([0, 2, 4, 6, 8])

In [20]:
X = -X
X

array([ 0, -1, -2, -3, -4])

In [21]:
np.absolute(X)

array([0, 1, 2, 3, 4])

In [23]:
array_linspace = np.linspace(0,np.pi,10)

# Divide el intervalo de 0 a pi en 10 partes
array_linspace

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [25]:
array_suma = np.random.random(100)
array_suma.sum()

50.22974697226334

In [32]:
a = np.array([0,1,2])
b = a.reshape((3,1))
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]
